apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    version: v1
    app: players
  name: players-v1
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: players
  template:
    metadata:
      labels:
        app: players
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9999"
        prometheus.io/path: "actuator/prometheus"
    spec:
      containers:
        - image: claudioed/players-spring:latest
          imagePullPolicy: Always
          env:
            - name: JAEGER_ENDPOINT
              value: http://jaeger-collector.observability.svc.cluster.local:14268/api/traces
          resources:
            requests:
              memory: "256Mi"
              cpu: "1000m"
            limits:
              memory: "512Mi"
              cpu: "1200m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9999
              scheme: HTTP
            initialDelaySeconds: 1
          name: players
          ports:
            - containerPort: 9999
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9999
              scheme: HTTP
            initialDelaySeconds: 1