apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: championships-service-monitor
spec:
  selector:
    matchLabels:
      app: championships
  endpoints:
    - port: "http"
      path: "/actuator/prometheus"