apiVersion: v1
kind: Service
metadata:
  labels:
    app: players
  name: players
spec:
  ports:
    - name: http
      port: 9999
      protocol: TCP
      targetPort: 9999
  selector:
    app: players